// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkPJZh3-W6uvGan-fcGKrIvnJAJmlaPYk',
    appId: '1:662455682381:web:7fdeaaa523d5b07f07a304',
    messagingSenderId: '662455682381',
    projectId: 'mc-naver-book-review',
    authDomain: 'mc-naver-book-review.firebaseapp.com',
    storageBucket: 'mc-naver-book-review.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7v6dOqAlg_NtMf5lVWUZkRZkdWDPs54Y',
    appId: '1:662455682381:android:f82e5498b6f5700a07a304',
    messagingSenderId: '662455682381',
    projectId: 'mc-naver-book-review',
    storageBucket: 'mc-naver-book-review.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYDFRL4V3BmEdpQSEmAWyIsMs1igTGO0',
    appId: '1:662455682381:ios:44b8cb85da9ee9e007a304',
    messagingSenderId: '662455682381',
    projectId: 'mc-naver-book-review',
    storageBucket: 'mc-naver-book-review.firebasestorage.app',
    iosBundleId: 'com.minchan.bookreview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYDFRL4V3BmEdpQSEmAWyIsMs1igTGO0',
    appId: '1:662455682381:ios:44b8cb85da9ee9e007a304',
    messagingSenderId: '662455682381',
    projectId: 'mc-naver-book-review',
    storageBucket: 'mc-naver-book-review.firebasestorage.app',
    iosBundleId: 'com.minchan.bookreview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkPJZh3-W6uvGan-fcGKrIvnJAJmlaPYk',
    appId: '1:662455682381:web:7a4a4679a3ffb47807a304',
    messagingSenderId: '662455682381',
    projectId: 'mc-naver-book-review',
    authDomain: 'mc-naver-book-review.firebaseapp.com',
    storageBucket: 'mc-naver-book-review.firebasestorage.app',
  );
}
